FROM ubuntu:xenial

COPY sources_xenial.list fibjs_build_ubuntu.sh /build/

RUN cd /build && mv sources_xenial.list /etc/apt/sources.list && apt-get update && apt-get install wget software-properties-common -y && ./fibjs_build_ubuntu.sh -y